### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by hvgazula**
Note that none of us can merge this until we get the 2 approved reviews. So, @VeritasJoker, you do the first review, followed by @zkokaja, who will then merge it. Sounds good?

### CODE REVIEW

**Comment by hvgazula** [comment]
The issues fixed in this PR can be seen in commit messages.

**Review by VeritasJoker — COMMENTED** [review]
Nice work! Can I ask two things. First, do we want to include the index changes in this pr or not (hassonlab/247-encoding#50)? Second, just to make sure, the reason we changed [this](https://github.com/hassonlab/247-pickling/blob/762a4219c989356807262f81f6d2054fe9a650bf/scripts/tfsemb_config.py#L25) is for static embeddings? Would it work for all models?

**Comment by hvgazula** [comment]
No, that will be a PR for next week. For now, we are merging as and when the issues are addressed. Think of this as the weekly PR.  The answer to the second question is yes, of course.

> Nice work! Can I ask two things. First, do we want to include the index changes in this pr or not ([hassonlab/247-encoding#50](https://github.com/hassonlab/247-encoding/issues/50))? Second, just to make sure, the reason we changed [this](https://github.com/hassonlab/247-pickling/blob/762a4219c989356807262f81f6d2054fe9a650bf/scripts/tfsemb_config.py#L25) is for static embeddings? Would it work for all models?

**Comment by hvgazula** [comment]
nice work..huh? are we working for the first time? :P. You are trying the sandwich approach.

**Review by VeritasJoker — APPROVED** [review]

**Comment by VeritasJoker** [comment]
> nice work..huh? are we working for the first time? :P. You are trying the sandwich approach.

lol we can't even give compliments now? I'm just really impressed with the accelerator stuff. Besides I didn't say nice things at the end so at best this is an open sandwich : )

**Comment by hvgazula** [comment]
I agree. The accelerator part was pretty cool. Saves a lot of chopping and changing time.

**Review by zkokaja — APPROVED** [review]
Looks good to me.

**Comment by hvgazula** [comment]
Thank you sir.

**Pull request merged**
