### PR TITLE
added list of models to use with git lfs

### PR DESCRIPTION
**Pull request by hvgazula**
check if caching was successful

### CODE REVIEW

**Comment by hvgazula** [comment]
@VeritasJoker  and @miahong Can you two review this PR and let me know if you have any issues before I merge this with the main branch. @miahong This commit has code to address the issue with opt (6.7B and 30B). So, please take a close look at what's being done and approve once you are okay.

**Comment by hvgazula** [comment]
https://github.com/hassonlab/247-pickling/issues/61

**Review by VeritasJoker — COMMENTED** [review]
It seems like we are caching them to the same directory so to me it's fine. I do like the consistency across models but I think it's ok if they are downloaded to the same place and loaded in the same way. If it's too much work changing all the models to git clone then don't bother.

**Comment by hvgazula** [comment]
There are some very minor differences in how the models are loaded but otherwise, they are absolutely similar. The details are in the huggingface link I posted in the issue convo.

**Pull request merged**
