### PR TITLE
small fixs for generating and concatenating embeddings

### PR DESCRIPTION
**Pull request by miahong**

### CODE REVIEW

**Comment by VeritasJoker** [comment]
Hey Mia, add these two lines to tfsemb_concat.py, after line 78:
    if '/' in stra:
        stra = args.embedding_type.split("/")[-1]

This should solve the problem where slash creates folders. Then we don't need to modify the EMB_TYPE argument in the Makefile

**Comment by miahong** [comment]
that works! thanks!

**Comment by hvgazula** [comment]
In the interest of simplifying file naming and minimizing code modifications to encoding, I am considering removing the first part of the model name. For example, if a model name is `a/b`, I will just keep `b`. I am sorry, I had to make this decision a little late in the day. Please vote your approval with a 👍 or disapproval with 👎. @VeritasJoker @miahong

**Comment by hvgazula** [comment]
closed because the changes have been made manually.

**Comment by VeritasJoker** [comment]
I couldn't find the original comment @hvgazula but I'm fine either way. As long as the pickles we generated only has the last part of the model name we should be fine

**Pull request closed without merging**
