### PR TITLE
Revert "Dev to Main 20230126"

### PR DESCRIPTION
**Pull request by zkokaja**
Reverts hassonlab/247-pickling#144 so we can merge instead of rebase

### CODE REVIEW

**Comment by hvgazula** [comment]
https://www.atlassian.com/git/tutorials/merging-vs-rebasing never been a fan of rebase but what exactly is the reason (to choose this over merge) other than to avoid that extra merge commit? 🤷

**Comment by hvgazula** [comment]
look overloaded 
image

**Comment by VeritasJoker** [comment]
Yeah we won't do the rebase in the future

**Comment by zkokaja** [comment]
Because dev will be behind main by one commit, but rebase didn't work for us either

**Comment by hvgazula** [comment]
> Because dev will be behind main by one commit, but rebase didn't work for us either

Okay. Probably, next time, the PR creator should do the merging as well to avoid those bloated commit messages :). @VeritasJoker This one's on you 🤣.

**Pull request closed without merging**
